
@BASE_URL = http://localhost:3000/api

###
GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/5

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
   "name" : "Berkay3",
   "userName" : "1",
   "email" : "atasoy18324@gmail.com",
   "password" : "12344"
}

###
PATCH {{BASE_URL}}/users/622e356acee9be20dcc1717d
Content-Type: application/json

{
   "name" : "Hasan3",
   "userName" : "4444"
}

###
DELETE  {{BASE_URL}}/users/622e356acee9be20dcc1717
Content-Type: application/json